# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-14 22:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Userprofiledetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('offers', models.CharField(max_length=50)),
                ('package', models.CharField(max_length=50)),
                ('servicedetails', models.CharField(db_column='serviceDetails', max_length=50)),
                ('productdescription', models.CharField(db_column='productDescription', max_length=50)),
                ('aboutproduct', models.CharField(db_column='aboutProduct', max_length=50)),
                ('aboutus', models.CharField(db_column='aboutUs', max_length=50)),
            ],
            options={
                'db_table': 'userprofiledetails',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='States',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cityNum', models.IntegerField(blank=True, null=True)),
                ('city_name', models.CharField(max_length=50)),
                ('city_state', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
